// question.js

const quizData = {
  // --- Danh mục 1: Tiếng Anh (Chủ đề Giáo dục) ---
  "English - Education": [
    {
      id: 1,
      tag: "Education",
      type: "MCQ",
      q: "What does the word 'student' mean?",
      options: [
        "A person who teaches",
        "A person who learns",
        "A school building",
        "A subject",
      ],
      a: 1,
      explanation: "'Student' là người học, người đi học.",
    },
    {
      id: 2,
      tag: "Education",
      type: "MCQ",
      q: "What is a 'teacher'?",
      options: [
        "Someone who studies",
        "Someone who teaches",
        "A classroom",
        "A lesson",
      ],
      a: 1,
      explanation: "'Teacher' là người dạy học.",
    },
    {
      id: 3,
      tag: "Education",
      type: "MCQ",
      q: "The word 'school' refers to:",
      options: ["A job", "A place for learning", "A test", "A subject"],
      a: 1,
      explanation: "'School' là nơi học tập.",
    },
    {
      id: 4,
      tag: "Education",
      type: "MCQ",
      q: "What does 'classroom' mean?",
      options: [
        "A teacher",
        "A subject",
        "A room where students study",
        "A book",
      ],
      a: 2,
      explanation: "'Classroom' là phòng học nơi học sinh học tập.",
    },
    {
      id: 5,
      tag: "Education",
      type: "MCQ",
      q: "What is a 'lesson'?",
      options: [
        "A school year",
        "A unit of teaching",
        "A student",
        "A building",
      ],
      a: 1,
      explanation: "'Lesson' là một buổi hoặc phần bài học.",
    },
    {
      id: 6,
      tag: "Education",
      type: "MCQ",
      q: "The word 'homework' means:",
      options: [
        "Work done at home for school",
        "A school subject",
        "A class activity",
        "A final exam",
      ],
      a: 0,
      explanation: "'Homework' là bài tập về nhà.",
    },
    {
      id: 7,
      tag: "Education",
      type: "MCQ",
      q: "What does 'exam' refer to?",
      options: ["A lesson", "A test", "A teacher", "A classroom"],
      a: 1,
      explanation: "'Exam' là bài kiểm tra hoặc kỳ thi.",
    },
    {
      id: 8,
      tag: "Education",
      type: "MCQ",
      q: "The word 'subject' means:",
      options: [
        "A student",
        "A school rule",
        "An area of study",
        "A classroom",
      ],
      a: 2,
      explanation: "'Subject' là môn học.",
    },
    {
      id: 9,
      tag: "Education",
      type: "MCQ",
      q: "What is a 'schedule'?",
      options: ["A book", "A plan of classes and times", "A test", "A student"],
      a: 1,
      explanation: "'Schedule' là thời khóa biểu.",
    },
    {
      id: 10,
      tag: "Education",
      type: "MCQ",
      q: "The word 'library' refers to:",
      options: [
        "A classroom",
        "A place to borrow books",
        "A teacher",
        "A test room",
      ],
      a: 1,
      explanation: "'Library' là thư viện – nơi đọc và mượn sách.",
    },
    {
      id: 11,
      tag: "Education",
      type: "MCQ",
      q: "What does 'study' mean?",
      options: ["To teach", "To learn and practice", "To test", "To rest"],
      a: 1,
      explanation: "'Study' nghĩa là học tập.",
    },
    {
      id: 12,
      tag: "Education",
      type: "MCQ",
      q: "The word 'grade' means:",
      options: [
        "A classroom",
        "A teacher",
        "A level or score in school",
        "A subject",
      ],
      a: 2,
      explanation: "'Grade' là điểm số hoặc khối/lớp học.",
    },
    {
      id: 13,
      tag: "Education",
      type: "MCQ",
      q: "What is a 'course'?",
      options: [
        "A single lesson",
        "A long program of study",
        "A classroom",
        "A test",
      ],
      a: 1,
      explanation: "'Course' là khóa học.",
    },
    {
      id: 14,
      tag: "Education",
      type: "MCQ",
      q: "The word 'certificate' means:",
      options: [
        "A school",
        "A written proof of achievement",
        "A subject",
        "A lesson",
      ],
      a: 1,
      explanation: "'Certificate' là chứng chỉ.",
    },
    {
      id: 15,
      tag: "Education",
      type: "MCQ",
      q: "What does 'education' mean?",
      options: [
        "Teaching and learning",
        "A classroom",
        "A test",
        "A school subject",
      ],
      a: 0,
      explanation: "'Education' là quá trình giáo dục và học tập.",
    },
  ],

  // --- Danh mục 2: HCI (Bạn có thể thêm lại dữ liệu HCI vào đây nếu muốn) ---
  "HCI & UX Design": [
    {
      id: 101,
      tag: "HCI",
      type: "MCQ",
      q: "HCI là viết tắt của từ gì?",
      options: [
        "Human Computer Interaction",
        "Human Control Interface",
        "Human Connection Internet",
        "High Computer Intelligence",
      ],
      a: 0,
      explanation: "HCI là Human-Computer Interaction (Tương tác Người-Máy).",
    },
    {
      id: 102,
      tag: "HCI",
      type: "MCQ",
      q: "Nguyên tắc nào KHÔNG thuộc 10 Heuristics của Jakob Nielsen?",
      options: [
        "Visibility of system status",
        "User control and freedom",
        "Consistency and standards",
        "Make it pop and shiny",
      ],
      a: 3,
      explanation: "'Make it pop' không phải là nguyên tắc thiết kế UX chuẩn.",
    },
  ],
};
